---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
data:
  url: {{ .Values.url }}
  driver-class-name: {{ index .Values "driver-class-name" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    create database frontiers;
    use frontiers;

    drop table if exists book_attribute_entity CASCADE;
    drop table if exists book_entity CASCADE;
    drop table if exists favorite_user_mapping CASCADE;
    drop table if exists future_product_entity CASCADE;
    drop table if exists future_trade_entity CASCADE;
    drop table if exists trading_agency_attribute_entity CASCADE;
    drop table if exists trading_agency_entity CASCADE;
    drop table if exists user_book_mapping CASCADE;
    drop table if exists user_entity CASCADE;

    drop sequence if exists hibernate_sequence;
    drop sequence if exists product_sequence;
    drop sequence if exists trade_sequence;

    create sequence hibernate_sequence start with 1 increment by 1;
    create sequence trade_sequence start with 100000070 increment by 1;
    create sequence product_sequence start with 100000060 increment by 1;

    create table book_attribute_entity (id bigint not null, attribute_key varchar(255), attribute_value varchar(255), book_code varchar(255) not null, primary key (id));
    create table book_entity (code varchar(255) not null, location varchar(255), name varchar(255), profit_code varchar(255), status boolean not null, trading_agency_entity_id bigint, primary key (code));
    create table favorite_user_mapping (favorite_user_id varchar(255), user_id varchar(255) not null, primary key (user_id));
    create table future_product_entity (product_id bigint not null, entered_date bigint not null, entered_user_id varchar(255) not null, updated_date bigint not null, updated_user_id varchar(255) not null, comments varchar(255), contract_size numeric(19,2), currency varchar(255), maturity_date varchar(255), payment_date varchar(255), product_code varchar(255), product_name varchar(255), settle_type varchar(255), underlying_code varchar(255), version_no bigint not null, primary key (product_id));
    create table future_trade_entity (trade_id bigint not null, entered_date bigint not null, entered_user_id varchar(255) not null, updated_date bigint not null, updated_user_id varchar(255) not null, book_code varchar(255), broker_code varchar(255), buy_sell varchar(255), currency varchar(255), night_deal boolean not null, nominal numeric(19,2), price numeric(19,2), quantity numeric(19,2), settle_date varchar(255), status varchar(255), trade_date bigint, trader_id varchar(255), version_no bigint not null, product_id bigint, primary key (trade_id));
    create table trading_agency_attribute_entity (id bigint not null, attribute_key varchar(255), attribute_value varchar(255), trading_agency_entity_id bigint not null, primary key (id));
    create table trading_agency_entity (id bigint not null, code varchar(255), name varchar(255), parent_id bigint not null, roles varchar(255), status boolean not null, primary key (id));
    create table user_book_mapping (user_id varchar(255) not null, book_code varchar(255) not null);
    create table user_entity (id varchar(255) not null, location varchar(255), name varchar(255), trader_id varchar(255), transaction_branch_code varchar(255), primary key (id));

    alter table book_attribute_entity add constraint FKdnxxn7kutwbq4b40x7gdt5gt3 foreign key (book_code) references book_entity;
    alter table trading_agency_attribute_entity add constraint FKdnxxn7kutwbq4b40x7gdt5gt4 foreign key (trading_agency_entity_id) references trading_agency_entity;
    alter table future_product_entity add constraint UK_id8ybln0ms01yjo85qp8ix4gq unique (product_code);
    alter table book_entity add constraint FK6t1ti5ww4w3v5pnbq8p2a2sxc foreign key (trading_agency_entity_id) references trading_agency_entity;
    alter table favorite_user_mapping add constraint FKdnxxn7kutwbq4b40x7gdt5gtd foreign key (favorite_user_id) references user_entity;
    alter table favorite_user_mapping add constraint FKdkaocdpjhk2jl4u3mokedc89h foreign key (user_id) references user_entity;
    alter table future_trade_entity add constraint FKihb0qoeye8x9vs7edq8g4wili foreign key (product_id) references future_product_entity;
    alter table user_book_mapping add constraint FK56m6pu7ppxq923qvyjbm4r850 foreign key (book_code) references book_entity;
    alter table user_book_mapping add constraint FK3mxod6ox730ejeihe2fpllvrr foreign key (user_id) references user_entity;
