apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.source }}:{{ .Values.image.version }}
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
